Repository WDAqua/Qanary, pull requests merged in 2023-12, with the labels that each got.

#220 [Snyk] Upgrade io.swagger.core.v3:swagger-core-jakarta from 2.2.17 to 2.2.18
  qanary_pipeline-template/pom.xml
Labels: dependencies

#223 Added SELECT-Query
  qanary_commons/pom.xml
  qanary_commons/src/main/resources/queries/select_all_annotationsWithSelectorAndPosition.rq
Labels: enhancement

#226 [Snyk] Upgrade @babel/core from 7.23.2 to 7.23.3
  qanary-configuration-frontend/package-lock.json
  qanary-configuration-frontend/package.json
Labels: dependencies

#228 [Snyk] Upgrade de.codecentric:spring-boot-admin-server from 2.7.12 to 2.7.13
  qanary_pipeline-template/pom.xml
Labels: dependencies

#229 [Snyk] Upgrade de.codecentric:spring-boot-admin-starter-client from 2.7.12 to 2.7.13
  qanary_component-template/pom.xml
Labels: dependencies

#230 Update docker-deployment.yml
  .github/workflows/docker-deployment.yml
Labels: enhancement

#233 Bugfix: SELECT-Query for type `AnnotationOfAnswerJSON`
  qanary_commons/pom.xml
  qanary_commons/src/main/resources/queries/select_all_AnnotationOfAnswerJson.rq
Labels: bug

#235 [Snyk] Upgrade @babel/core from 7.23.3 to 7.23.5
  qanary-configuration-frontend/package-lock.json
  qanary-configuration-frontend/package.json
Labels: dependencies

#219 Update select_all_AnnotationOfClass.rq
  qanary_commons/pom.xml
  qanary_commons/src/main/resources/queries/select_all_AnnotationOfClass.rq
Labels: enhancement

#234 [Snyk] Upgrade de.codecentric:spring-boot-admin-server from 2.7.13 to 2.7.14
  qanary_pipeline-template/pom.xml
Labels: dependencies

#231 [Snyk] Upgrade de.codecentric:spring-boot-admin-starter-client from 2.7.12 to 2.7.13
  qanary_component-archetype/src/main/resources/archetype-resources/pom.xml
Labels: dependencies

#236 [Snyk] Upgrade de.codecentric:spring-boot-admin-starter-client from 2.7.12 to 2.7.14
  qanary_commons/pom.xml
Labels: dependencies

#237 [Snyk] Upgrade de.codecentric:spring-boot-admin-starter-client from 2.7.13 to 2.7.14
  qanary_component-archetype/src/main/resources/archetype-resources/pom.xml
Labels: dependencies
