Repository WDAqua/Qanary, pull requests merged in 2024-07, with the labels that each got.

#288 Fix registration for questionanswering frontend
  qanary_pipeline-template/pom.xml
  qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/QanaryComponentRegistrationChangeNotifier.java
  qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/QanaryQuestionAnsweringController.java
  qanary_pipeline-template/src/main/resources/templates/lib/reusableforms.html
Labels: enhancement

#286 [Snyk] Upgrade org.glassfish.jaxb:jaxb-runtime from 4.0.4 to 4.0.5
  qanary_pipeline-template/pom.xml
Labels: dependencies, java

#278 Extend qanary pipeline as component
  qanary_commons/pom.xml
  qanary_commons/src/main/java/eu/wdaqua/qanary/business/QanaryConfigurator.java
  qanary_commons/src/main/java/eu/wdaqua/qanary/commons/QanaryQuestion.java
  qanary_commons/src/main/java/eu/wdaqua/qanary/commons/QanaryUtils.java
  qanary_commons/src/main/java/eu/wdaqua/qanary/commons/triplestoreconnectors/QanaryTripleStoreConnector.java
  qanary_commons/src/main/java/eu/wdaqua/qanary/commons/triplestoreconnectors/QanaryTripleStoreConnectorInMemory.java
  qanary_commons/src/main/java/eu/wdaqua/qanary/commons/triplestoreconnectors/QanaryTripleStoreConnectorQanaryInternal.java
  qanary_commons/src/main/java/eu/wdaqua/qanary/commons/triplestoreconnectors/QanaryTripleStoreConnectorStardog.java
  qanary_commons/src/main/java/eu/wdaqua/qanary/commons/triplestoreconnectors/QanaryTripleStoreConnectorVirtuoso.java
  qanary_commons/src/main/java/eu/wdaqua/qanary/commons/triplestoreconnectors/QanaryTripleStoreProxy.java
  qanary_commons/src/test/java/qa/commons/PriorConversationTest.java
  qanary_component-parent/pom.xml
  qanary_component-template/pom.xml
  qanary_component-template/src/main/java/eu/wdaqua/qanary/component/QanaryComponent.java
  qanary_component-template/src/main/java/eu/wdaqua/qanary/component/QanaryComponentConfiguration.java
  qanary_component-template/src/main/java/eu/wdaqua/qanary/component/QanaryComponentDescriptionController.java
  qanary_component-template/src/main/java/eu/wdaqua/qanary/component/QanaryService.java
  qanary_component-template/src/main/java/eu/wdaqua/qanary/component/QanaryServiceController.java
  qanary_component-template/src/main/java/eu/wdaqua/qanary/component/QanaryServiceControllerRoot.java
  qanary_pipeline-template/pom.xml
  qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/QanaryPipeline.java
  qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/QanaryPipelineComponent.java
  qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/QanaryComponentsManagementController.java
  qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/QanaryQuestionAnsweringController.java
  qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/QanarySparqlProtocolController.java
  qanary_pipeline-template/src/main/resources/application.properties
  qanary_pipeline-template/src/main/resources/insert_constructed_triples.rq
  qanary_pipeline-template/src/main/resources/pipeline_component_construct.rq
  qanary_pipeline-template/src/main/resources/select_questionId.rq
  qanary_pipeline-template/src/test/java/eu/wdaqua/qanary/QanaryComponentRegistrationChangeNotifierTest.java
  qanary_pipeline-template/src/test/java/eu/wdaqua/qanary/QanaryPipelineComponentTest.java
  qanary_pipeline-template/src/test/java/eu/wdaqua/qanary/QanaryQuestionAnsweringControllerTest.java
  qanary_pipeline-template/src/test/java/eu/wdaqua/qanary/web/QanaryGerbilControllerTest.java
  qanary_pipeline-template/src/test/java/eu/wdaqua/qanary/web/QanaryPipelineConfigurationAccessTest.java
  qanary_pipeline-template/src/test/resources/constructQueryFromModelTestResultQuery
Labels: enhancement

#238 [Snyk] Upgrade de.codecentric:spring-boot-admin-starter-client from 2.6.11 to 2.7.14
  qanary_component-template/pom.xml
Labels: dependencies
