Repository WDAqua/Qanary, pull requests merged in 2025-01, with the labels that each got.

#308 [Snyk] Upgrade org.yaml:snakeyaml from 2.2 to 2.3
  qanary_pipeline-template/pom.xml
Labels: dependencies, java

#312 [Snyk] Upgrade @babel/core from 7.25.2 to 7.25.7
  qanary-configuration-frontend/package-lock.json
  qanary-configuration-frontend/package.json
Labels: dependencies

#317 [Snyk] Upgrade io.swagger.core.v3:swagger-core-jakarta from 2.2.23 to 2.2.27
  qanary_pipeline-template/pom.xml
Labels: dependencies, java

#313 Method logging aspects
  qanary_commons/pom.xml
  qanary_commons/src/main/java/eu/wdaqua/qanary/explainability/annotations/LoggingAspectComponent.java
  qanary_commons/src/main/java/eu/wdaqua/qanary/explainability/annotations/LoggingAspectPipeline.java
  qanary_commons/src/main/java/eu/wdaqua/qanary/explainability/annotations/MethodObject.java
  qanary_commons/src/main/resources/queries/logging/insert_method_data.rq
  qanary_commons/src/test/java/qa/commons/LoggingAspectTest.java
  qanary_component-parent/pom.xml
  qanary_component-template/pom.xml
  qanary_pipeline-template/pom.xml
Labels: enhancement, java
